### ISSUE TITLE
Read/ Write

### ISSUE THREAD

**Issue by cmoore91** [bitbank2/Multi_BitBang#2]
Can you post an example going a little bit more into a use case of the Multi_I2CRead and Multi_I2CWrite functions??  I have successfully scanned and detected my devices as per your wonderful example, but am stuck with whats next.  I am trying to communicate with ultrasonic sensors (https://www.sparkfun.com/products/17777) and have no luck.  Thank you.

**Comment by bitbank2** [comment]
I updated my BitBang_I2C library to support multiple instances, so this multi_bitbang is no longer needed. I have a better example in the new library of how to read and write data to devices. It scans the bus and identifies known devices from a list:

https://github.com/bitbank2/BitBang_I2C
